### ISSUE TITLE
Fix Size and Spacing

### ISSUE THREAD

**Issue by karim-bakhsh** [ZalaaGaheez/HomeTwon-Scrimba#1]
Spacing a size are one of the most important thing while designing a webpage. Make sure that the parts and divs that are the same should have the same design, like sizing, coloring, width, height, and other stuff if looks good.

I have applied the followings for the div inside `.places` div.

```css
.places div {
    border: 1px solid black;
    width: 40rem;
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 20px 0;
}
```

Make sure you follow these things in the other parts of your webpage.

![image](https://github.com/ZalaaGaheez/HomeTwon-Scrimba/assets/128901215/b780e6e9-168c-4302-a618-13b0b564e268)
![image](https://github.com/ZalaaGaheez/HomeTwon-Scrimba/assets/128901215/d756c572-05d6-48d8-9315-62b6ba9bdd50)
